baseURL = "https://bienneenpoche.netlify.app"
title = "Biel-Bienne app"

languageCode = "fr"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

cleanDestinationDir = true
disableFastRender = true

removePathAccents = true

disableKinds = [ "taxonomy", "term", "robotsTXT", "RSS", "404"]
