# Configuration de l'allemand
[de]
contentDir = "content/de"
languageName = "Deutsch"
weight = 10

title = "Mehr über die Stadt Biel"
footer = "Ein Projekt der Stadt Biel"

# Activer un boutton d'urgence sur toutes les pages
# Il faut enlever le # des 3 lignes suivantes

# [de.params.emergency]
# title = "Notfall"
# url = "/de/notfall/"

# Configuration du français 
[fr]
contentDir = "content/fr"
languageName = "Français"
weight = 20

title = "Informations sur Bienne"
footer = "Un projet de la Ville de Bienne"


[fr.params.important]
title = "Important"
text = "Annonce importante sur **toutes** les pages (mais qui ne remplace pas la page!)."
 
# [fr.params.emergency]
# title = "Urgences absolue"
# text = """
# Gloups, tout merde!
# 
# Suite.
# 
# ![urgence aéroportée](https://cdn.pixabay.com/photo/2019/11/26/17/34/helicopter-4655049_1280.jpg)
# """
